projetoDjango/gerenciador_de_eventos/evento/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listar_eventos, name='lista_de_evento'),
    path('<int:evento_id>/', views.detalhes_evento, name='detalhe_do_evento'),
]

projetoDjango/gerenciador_de_eventos/gerenciador_de_eventos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('evento.urls')), 
]

projetoDjango/gerenciador_de_eventos/evento/models.py
from django.db import models

# Create your models here.

class Evento(models.Model):
    TIPOS_EVENTO = [
        ('show', 'Shows'),
        ('stand_up', 'Stand Up'),
        ('teatro', 'Apresentações Teatrais'),
        ('aniversario', 'Aniversário de Itapajé'),
        # Adicione outros tipos conforme necessário
    ]

    titulo = models.CharField(max_length=200)
    tipo = models.CharField(max_length=50, choices=TIPOS_EVENTO)
    data_inicio = models.DateField()
    data_fim = models.DateField(blank=True, null=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    gratuito = models.BooleanField(default=False)
    local = models.CharField(max_length=200)
    horario = models.TimeField()
    cidade = models.CharField(max_length=100)
    vagas = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.titulo

    

projetoDjango/gerenciador_de_eventos/evento/forms.py
# forms.py
from django import forms
from .models import Evento

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = [
            'titulo', 'tipo', 'data_inicio', 'data_fim', 'valor', 'gratuito',
            'local', 'horario', 'cidade', 'vagas'
        ]
        widgets = {
            'data_inicio': forms.DateInput(attrs={'type': 'date'}),
            'data_fim': forms.DateInput(attrs={'type': 'date'}),
            'horario': forms.TimeInput(attrs={'type': 'time'}),
            'valor': forms.NumberInput(attrs={'step': '0.01'}),
        }
        
    def clean(self):
        cleaned_data = super().clean()
        gratuito = cleaned_data.get('gratuito')
        valor = cleaned_data.get('valor')

        if gratuito and valor is not None:
            self.add_error('valor', 'Se a entrada é gratuita, o valor da entrada deve ser deixado em branco.')
        
        if not gratuito and valor is None:
            self.add_error('valor', 'Se a entrada não é gratuita, o valor da entrada deve ser informado.')

        return cleaned_data

projetoDjango/gerenciador_de_eventos/evento/views.py
from django.shortcuts import render, get_object_or_404
from .models import Evento
from .forms import EventoForm

def listar_eventos(request):
    form = EventoForm()        
    eventos = Evento.objects.all()
    return render(request, 'eventos/lista_de_evento.html', {'eventos': eventos, 'form':form})

def detalhes_evento(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)
    return render(request, 'detalhe_do_evento.html', {'evento': evento})

projetoDjango/gerenciador_de_eventos/templates/eventos/detalhe_do_evento.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{{ evento.titulo }}</title>
    
</head>
<body>
    <h1>{{ evento.titulo }}</h1>
    <p>Tipo: {{ evento.get_tipo_display }}</p>
    <p>Data: {{ evento.data_inicio }} {% if evento.data_fim %}a {{ evento.data_fim }}{% endif %}</p>
    <p>Horário: {{ evento.horario }}</p>
    <p>Local: {{ evento.local }}</p>
    <p>Cidade: {{ evento.cidade }}</p>
    <p>Valor: {% if evento.gratuito %}Gratuito{% else %}R$ {{ evento.valor }}{% endif %}</p>
    <p>Vagas: {% if evento.vagas %}{{ evento.vagas }}{% else %}Ilimitadas{% endif %}</p>
</body>
</html>

projetoDjango/gerenciador_de_eventos/templates/eventos/lista_de_evento.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Lista de Eventos</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>Eventos de Itapajé</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar Evento</button>
    </form>
    <ul>
        {% for evento in eventos %}
            <li>
                <a href="{% url 'detalhe_do_evento' evento.id %}">{{ evento.titulo }}</a>
                - {{ evento.get_tipo_display }} - {{ evento.cidade }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>